// Mocks generated by Mockito 5.4.6 from annotations
// in project_one_c3_team/test/viweModel/viweModel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:project_one_c3_team/api/auth/request/Forgot_Password_Request.dart'
    as _i13;
import 'package:project_one_c3_team/api/auth/request/Reset%20Password.dart'
    as _i17;
import 'package:project_one_c3_team/api/auth/request/sign_in_request.dart'
    as _i9;
import 'package:project_one_c3_team/api/auth/request/SignUpRequest.dart' as _i5;
import 'package:project_one_c3_team/api/auth/request/Verify_Reset_password.dart'
    as _i15;
import 'package:project_one_c3_team/api/auth/response/sign_in_response.dart'
    as _i8;
import 'package:project_one_c3_team/api/home/response/user_info_response.dart'
    as _i19;
import 'package:project_one_c3_team/core/errors/result/results.dart' as _i4;
import 'package:project_one_c3_team/domin/auth/use_case/ForgotPasswordUseCase.dart'
    as _i12;
import 'package:project_one_c3_team/domin/auth/use_case/ResetPasswordUseCase.dart'
    as _i16;
import 'package:project_one_c3_team/domin/auth/use_case/SignInUseCase.dart'
    as _i7;
import 'package:project_one_c3_team/domin/auth/use_case/SignUp_UsaCase.dart'
    as _i2;
import 'package:project_one_c3_team/domin/auth/use_case/VerifyResetCodeUseCase.dart'
    as _i14;
import 'package:project_one_c3_team/domin/home/model/Get_subjects_model.dart'
    as _i11;
import 'package:project_one_c3_team/domin/home/UsaCase/Get_subjects_Use_Case.dart'
    as _i10;
import 'package:project_one_c3_team/domin/home/UsaCase/get_user_info_use_case.dart'
    as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SignUp_UsaCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUp_UsaCase extends _i1.Mock implements _i2.SignUp_UsaCase {
  MockSignUp_UsaCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> signUp(_i5.SignUpRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [request]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#signUp, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [SignInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInUseCase extends _i1.Mock implements _i7.SignInUseCase {
  MockSignInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i8.Sign_in_response>> signIn(
    _i9.SignInRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [request]),
            returnValue: _i3.Future<_i4.Result<_i8.Sign_in_response>>.value(
              _i6.dummyValue<_i4.Result<_i8.Sign_in_response>>(
                this,
                Invocation.method(#signIn, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.Sign_in_response>>);
}

/// A class which mocks [Get_subject_Use_Case].
///
/// See the documentation for Mockito's code generation for more information.
class MockGet_subject_Use_Case extends _i1.Mock
    implements _i10.Get_subject_Use_Case {
  MockGet_subject_Use_Case() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i11.subject>>> Get_subjects_Data(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#Get_subjects_Data, [token]),
            returnValue: _i3.Future<_i4.Result<List<_i11.subject>>>.value(
              _i6.dummyValue<_i4.Result<List<_i11.subject>>>(
                this,
                Invocation.method(#Get_subjects_Data, [token]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i11.subject>>>);
}

/// A class which mocks [ForgotPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgotPasswordUseCase extends _i1.Mock
    implements _i12.ForgotPasswordUseCase {
  MockForgotPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> forgotPasswordSendCode(
    _i13.ForgotPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPasswordSendCode, [request]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#forgotPasswordSendCode, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [VerifyResetCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyResetCodeUseCase extends _i1.Mock
    implements _i14.VerifyResetCodeUseCase {
  MockVerifyResetCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> verifyResetCode(
    _i15.Verify_reset_password? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#verifyResetCode, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i16.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> resetPassword(_i17.Reset_Password? request) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [GetUserInfoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserInfoUseCase extends _i1.Mock
    implements _i18.GetUserInfoUseCase {
  MockGetUserInfoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i19.UserInfoResponse>> execute(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [token]),
            returnValue: _i3.Future<_i4.Result<_i19.UserInfoResponse>>.value(
              _i6.dummyValue<_i4.Result<_i19.UserInfoResponse>>(
                this,
                Invocation.method(#execute, [token]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i19.UserInfoResponse>>);
}
